//
//  Control.swift
//  Netrek
//
//  Moved from KeymapController.swift for shared access
//

import Foundation

enum Control: String, CaseIterable {
    case zeroKey = "0 key"
    case oneKey = "1 key"
    case twoKey = "2 key"
    case threeKey = "3 key"
    case fourKey = "4 key"
    case fiveKey = "5 key"
    case sixKey = "6 key"
    case sevenKey = "7 key"
    case eightKey = "8 key"
    case nineKey = "9 key"
    case spacebarKey = "spacebar key"
    case rightParenKey = ") key"
    case exclamationMarkKey = "! key"
    case atKey = "@ key"
    case percentKey = "% key"
    case poundKey = "# key"
    case lessThanKey = "< key"
    case greaterThanKey = "> key"
    case rightBracketKey = "] key"
    case leftBracketKey = "[ key"
    case leftMouse = "left mouse button"
    case otherMouse = "center mouse button"
    case rightMouse = "right mouse button"
    case leftCurly = "{ key"
    case rightCurly = "} key"
    case underscore = "_ key"
    case carrot = "^ key"
    case dollar = "$ key"
    case semicolon = "; key"
    case aKey = "a key"
    case bKey = "b key"
    case cKey = "c key"
    case dKey = "d key"
    case eKey = "e key"
    case fKey = "f key"
    case gKey = "g key"
    case hKey = "h key"
    case iKey = "i key"
    case jKey = "j key"
    case kKey = "k key"
    case lKey = "l key"
    case mKey = "m key"
    case nKey = "n key"
    case oKey = "o key"
    case pKey = "p key"
    case qKey = "q key"
    case rKey = "r key"
    case sKey = "s key"
    case tKey = "t key"
    case uKey = "u key"
    case vKey = "v key"
    case wKey = "w key"
    case xKey = "x key"
    case yKey = "y key"
    case zKey = "z key"
    case AKey = "A key"
    case BKey = "B key"
    case CKey = "C key"
    case DKey = "D key"
    case EKey = "E key"
    case FKey = "F key"
    case GKey = "G key"
    case HKey = "H key"
    case IKey = "I key"
    case JKey = "J key"
    case KKey = "K key"
    case LKey = "L key"
    case MKey = "M key"
    case NKey = "N key"
    case OKey = "O key"
    case PKey = "P key"
    case QKey = "Q key"
    case RKey = "R key"
    case SKey = "S key"
    case TKey = "T key"
    case UKey = "U key"
    case VKey = "V key"
    case WKey = "W key"
    case XKey = "X key"
    case YKey = "Y key"
    case ZKey = "Z key"
    case asteriskKey = "* key"
}

enum Command: String, CaseIterable {
    case speedZero = "Set speed 0"
    case speedOne = "Set speed 1"
    case speedTwo = "Set speed 2"
    case speedThree = "Set speed 3"
    case speedFour = "Set speed 4"
    case speedFive = "Set speed 5"
    case speedSix = "Set speed 6"
    case speedSeven = "Set speed 7"
    case speedEight = "Set speed 8"
    case speedNine = "Set speed 9"
    case speedTen = "Set speed 10"
    case speedEleven = "Set speed 11"
    case speedTwelve = "Set speed 12"
    case speedMax = "Set speed maximum"
    case speedHalf = "Set speed half"
    case speedDecrease = "Decrease speed 1"
    case speedIncrease = "Speed increase 1"
    case setCourse = "Set course"
    case beamUp = "Beam up armies"
    case beamDown = "Beam down armies"
    case bomb = "Bomb"
    case cloak = "Toggle cloak"
    case cloakUp = "Activate cloak"
    case cloakDown = "Deactivate cloak"
    case coup = "Coup own home planet"
    case detOwn = "Detonate own torpedoes"
    case detEnemy = "Detonate enemy torpedoes"
    case dockingPermission = "Docking Permission Toggle"
    case fireTorpedo = "Fire torpedo"
    case firePlasma = "Fire plasma"
    case fireLaser = "Fire laser"
    case information = "Information"
    case lockDestination = "Lock onto Destination"
    case lockStarbasePlanet = "Lock onto starbase or Planet"
    case lowerShields = "Lower shields"
    case nothing = "Nothing"
    case orbit = "Orbit"
    case pressorBeam = "Pressor beam toggle"
    case pressorOn = "Pressor beam on"
    case raiseShields = "Raise shields"
    case refit = "Refit (unused: use launch ship menu)"
    case repair = "Repair"
    case toggleShields = "Toggle shields"
    case tractorPressorOff = "Tractor and pressor beams off"
    case tractorBeam = "Tractor beam toggle"
    case tractorOn = "Tractor beam on"
    case quitGame = "Self destruct and quit game"
    case practiceRobot = "Send in practice robot"
}
